// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowAPI.Data;

#nullable disable

namespace ReviewAPI.Migrations.ShowDb
{
    [DbContext(typeof(ShowDbContext))]
    [Migration("20250604062056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ShowAPI.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isWatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Sopranos",
                            Username = "mannydelgado",
                            isWatched = false
                        },
                        new
                        {
                            Id = 2,
                            Title = "The Office",
                            Username = "mannydelgado",
                            isWatched = false
                        },
                        new
                        {
                            Id = 3,
                            Title = "Friends",
                            Username = "mannydelgado",
                            isWatched = true
                        },
                        new
                        {
                            Id = 4,
                            Title = "Spongebob",
                            Username = "mannydelgado",
                            isWatched = true
                        },
                        new
                        {
                            Id = 5,
                            Title = "Star Trek: The Next Generation",
                            Username = "phil_dunphy",
                            isWatched = false
                        },
                        new
                        {
                            Id = 6,
                            Title = "Stranger Things",
                            Username = "phil_dunphy",
                            isWatched = false
                        },
                        new
                        {
                            Id = 7,
                            Title = "Rick and Morty",
                            Username = "phil_dunphy",
                            isWatched = true
                        },
                        new
                        {
                            Id = 8,
                            Title = "Lost",
                            Username = "phil_dunphy",
                            isWatched = true
                        },
                        new
                        {
                            Id = 10,
                            Title = "The Office",
                            Username = "cam_tucker",
                            isWatched = true
                        },
                        new
                        {
                            Id = 11,
                            Title = "Overcompensating",
                            Username = "cam_tucker",
                            isWatched = false
                        },
                        new
                        {
                            Id = 12,
                            Title = "Euphoria",
                            Username = "cam_tucker",
                            isWatched = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
